import { fixture } from "./fixture.js";
import { classifySeries, planVariance, scopedDowntimePareto, qualityBalance, STATES } from "./engines.js";

const KEY="flowPilotStateV03";
const el=id=>document.getElementById(id);
const makeId=()=>globalThis.crypto?.randomUUID?.() ?? `local-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const labels={HEALTHY:"Healthy",PRESSURE:"Pressure",POSSIBLE_CONSTRAINT:"Possible constraint",STARVED:"Starved",UNKNOWN:"Unknown",PLANNED_STOP:"Planned stop",UNPLANNED_STOP:"Unplanned stop",PLANNED_BUFFER:"Planned buffer",CONFLICTED:"Conflicted data"};
let pilot=JSON.parse(localStorage.getItem(KEY)||"null");

const demoConfig={style:fixture.order.style,target:fixture.order.target,operations:fixture.operations,requiredRate:60,comparable:true};
const cfg=()=>pilot?.mode==="pilot"?pilot.config:demoConfig;
const isOpen=()=>pilot?.mode==="pilot"&&pilot.status==="OPEN";
function persist(){if(pilot?.mode==="pilot")localStorage.setItem(KEY,JSON.stringify(pilot));}
function audit(action,details={}){pilot.audit.push({id:makeId(),at:new Date().toISOString(),action,details});}
function requireOpen(statusEl){if(isOpen())return true;if(statusEl)statusEl.textContent="Not saved: this shift is closed.";return false;}

document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");el(b.dataset.view).classList.add("active");}));

function demoSeries(op){return fixture.observations[op].map((r,i)=>({intervalStart:new Date(`2026-10-05T${9+i}:00:00Z`),intervalEnd:new Date(`2026-10-05T${10+i}:00:00Z`),goodOutput:r[0],queueBefore:r[1],plannedStopMinutes:0,unplannedStopMinutes:0}));}
function localSeries(op){return pilot.observations.filter(x=>x.operation===op).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)).map(x=>({intervalStart:new Date(new Date(x.createdAt)-x.minutes*60000),intervalEnd:new Date(x.createdAt),goodOutput:x.goodOutput,queueBefore:x.queueBefore,plannedStopMinutes:x.stop==="planned"?x.minutes:0,unplannedStopMinutes:x.stop==="unplanned"?x.minutes:0,intentionalBuffer:x.intentionalBuffer===true}));}

const states=new Map();
function renderRadar(){const c=cfg();el("target").textContent=c.target;el("flow-list").innerHTML="";states.clear();c.operations.forEach(op=>{const series=pilot?.mode==="pilot"?localSeries(op):demoSeries(op);let result={state:STATES.UNKNOWN,reasons:["No observations yet"]};if(!c.comparable)result={state:STATES.UNKNOWN,reasons:["Rate comparison disabled because transfer units are not confirmed comparable"]};else if(series.length)result=classifySeries({observations:series,required:c.requiredRate,minQueue:5,persistenceIntervals:2});const latest=series.at(-1);states.set(op,{series,result,latest});const b=document.createElement("button");b.className="flow-card";b.innerHTML=`<div class="flow-top"><span class="flow-name">${op}</span><span class="badge ${result.state}">${labels[result.state]||result.state}</span></div><div class="flow-stats"><div><strong>${latest?.goodOutput??"—"}</strong><small>good / interval</small></div><div><strong>${latest?.queueBefore??"—"}</strong><small>WIP waiting</small></div></div>`;b.onclick=()=>renderDetail(op);el("flow-list").appendChild(b);});if(c.operations.length)renderDetail(c.operations.includes("Stitching")?"Stitching":c.operations[0]);}
function renderDetail(op){const {result,latest,series}=states.get(op),prev=series.at(-2);const evidence=latest?`${latest.goodOutput??"unknown"} good · WIP ${prev?.queueBefore??"unknown"} → ${latest.queueBefore??"unknown"}`:"No observation recorded yet.";el("explanation").innerHTML=`<p class="kicker">${op}</p><h3><span class="badge ${result.state}">${labels[result.state]||result.state}</span></h3><ul class="reason-list">${result.reasons.map(r=>`<li>${r}</li>`).join("")}</ul><p class="micro">Latest evidence: ${evidence}. This is a system signal, not a statement about worker responsibility.</p>`;}

function qualityTotals(){if(pilot?.mode!=="pilot")return fixture.quality;return pilot.quality.reduce((a,q)=>({inspected:a.inspected+q.inspected,firstPassGood:a.firstPassGood+(q.inspected-q.failed),failed:a.failed+q.failed,recovered:a.recovered+q.recovered,rejected:a.rejected+q.rejected,inRework:a.inRework+q.inRework}),{inspected:0,firstPassGood:0,failed:0,recovered:0,rejected:0,inRework:0});}
function renderLoss(){const c=cfg(),actual=pilot?.mode==="pilot"?(pilot.actualGood||0):427,pv=planVariance(c.target,actual);el("actual-output").textContent=actual;el("shortfall").textContent=pv.shortfall;const events=pilot?.mode==="pilot"?pilot.events.filter(e=>e.end):fixture.events;const p=events.length?scopedDowntimePareto(events):[],max=Math.max(...p.map(x=>x.minutes),1);el("pareto").innerHTML=p.length?p.map(x=>`<div class="pareto-row"><span>${x.scope} · ${x.category.replaceAll("_"," / ")}</span><div class="bar-track"><div class="bar" style="width:${100*x.minutes/max}%"></div></div><strong>${Math.round(x.minutes)}m</strong></div>`).join(""):"<p class='muted'>No resolved disturbance events yet.</p>";const q=qualityTotals();if(q.failed)qualityBalance({failed:q.failed,recovered:q.recovered,rejected:q.rejected,inRework:q.inRework});el("quality").innerHTML=[["Inspected",q.inspected],["First-pass good",q.firstPassGood],["First-pass failures",q.failed],["Recovered after rework",q.recovered],["Final rejects",q.rejected],["Still in rework",q.inRework]].map(([k,v])=>`<div class="quality-row"><span>${k}</span><strong>${v}</strong></div>`).join("");el("events").innerHTML=events.length?events.map(e=>`<div class="event-row"><strong>${e.operation}</strong><span>${e.category}</span><span class="condition">${e.condition||"No description"}${e.intervention?` · Action: ${e.intervention.action} · Outcome: ${e.intervention.outcome}`:""}</span></div>`).join(""):"<p class='muted'>No resolved disturbance events yet.</p>";}

function renderOpenIssues(){if(pilot?.mode!=="pilot"){el("open-issues").innerHTML="";return;}const open=pilot.events.filter(x=>!x.end);el("open-issues").innerHTML=open.map(x=>`<div class="open-issue"><span><strong>${x.operation}</strong> · ${x.category} · ${x.condition||"No note"}</span><button class="resolve" data-resolve="${x.id}" type="button">Resolve</button></div>`).join("");document.querySelectorAll("[data-resolve]").forEach(b=>b.onclick=()=>{if(!requireOpen(el("issue-status")))return;const event=pilot.events.find(x=>x.id===b.dataset.resolve);if(event&&!event.end){event.end=new Date().toISOString();audit("ISSUE_RESOLVED",{eventId:event.id});persist();refresh();}});}
function renderSelectors(){const ops=cfg().operations.map(op=>`<option>${op}</option>`).join("");el("op-select").innerHTML=ops;el("issue-op-select").innerHTML=ops;if(pilot?.mode==="pilot"){el("correction-select").innerHTML=pilot.observations.map(x=>`<option value="${x.id}">${x.operation} · ${new Date(x.createdAt).toLocaleTimeString()}</option>`).join("");el("intervention-event").innerHTML=pilot.events.filter(x=>x.end).map(x=>`<option value="${x.id}">${x.operation} · ${x.category}</option>`).join("");}else{el("correction-select").innerHTML="";el("intervention-event").innerHTML="";}}
function renderLifecycle(){el("shift-status").textContent=pilot?.mode==="pilot"?`Shift is ${pilot.status}. ${pilot.status==="CLOSED"?"Operational entries are locked.":"Entries are allowed."}`:"Synthetic demo mode";const items=pilot?.mode==="pilot"?pilot.audit.slice().reverse():[];el("audit-list").innerHTML=items.length?items.map(x=>`<div class="event-row"><strong>${x.action}</strong><span>${new Date(x.at).toLocaleString()}</span><span class="condition">${JSON.stringify(x.details)}</span></div>`).join(""):"<p class='muted'>No local audit entries yet.</p>";}
function refresh(){renderSelectors();renderRadar();renderLoss();renderOpenIssues();renderLifecycle();}

el("setup-form").onsubmit=e=>{e.preventDefault();const ops=el("operations-input").value.split(",").map(x=>x.trim()).filter(Boolean),target=Number(el("target-input").value),requiredRate=Number(el("rate-input").value);if(!ops.length||target<0||requiredRate<0)return;pilot={mode:"pilot",status:"OPEN",config:{style:el("style-input").value.trim()||"Local pilot",target,operations:[...new Set(ops)],requiredRate,comparable:el("comparable-input").checked},observations:[],events:[],quality:[],actualGood:0,audit:[],createdAt:new Date().toISOString()};audit("SHIFT_CREATED",{style:pilot.config.style,target});persist();refresh();};
el("update-form").onsubmit=e=>{e.preventDefault();if(!requireOpen(el("save-status")))return;const good=el("good-input").value===""?null:Number(el("good-input").value),wip=el("wip-input").value===""?null:Number(el("wip-input").value),minutes=Number(el("minutes-input").value);if((good!=null&&good<0)||(wip!=null&&wip<0)||!Number.isFinite(minutes)||minutes<=0){el("save-status").textContent="Not saved: invalid value.";return;}const record={id:makeId(),operation:el("op-select").value,goodOutput:good,queueBefore:wip,minutes,stop:el("stop-select").value,intentionalBuffer:el("buffer-input").checked,createdAt:new Date().toISOString(),revisions:[]};pilot.observations.push(record);audit("OBSERVATION_ADDED",{observationId:record.id,operation:record.operation});persist();el("save-status").textContent="Saved locally. Nothing was uploaded.";refresh();};
el("result-form").onsubmit=e=>{e.preventDefault();if(!requireOpen())return;const actual=Number(el("actual-input").value);if(!Number.isFinite(actual)||actual<0)return;const previous=pilot.actualGood;pilot.actualGood=actual;audit("GOOD_OUTPUT_UPDATED",{previous,next:actual});persist();refresh();};
el("issue-form").onsubmit=e=>{e.preventDefault();if(!requireOpen(el("issue-status")))return;const event={id:makeId(),operation:el("issue-op-select").value,category:el("category-select").value,condition:el("condition-input").value.trim(),start:new Date().toISOString(),end:null,attributionStatus:"OBSERVED",createdAt:new Date().toISOString()};pilot.events.push(event);audit("ISSUE_STARTED",{eventId:event.id,operation:event.operation,category:event.category});persist();el("condition-input").value="";el("issue-status").textContent="Issue started locally.";refresh();};
el("quality-form").onsubmit=e=>{e.preventDefault();if(!requireOpen(el("quality-status")))return;const inspected=Number(el("q-inspected").value),failed=Number(el("q-failed").value),recovered=Number(el("q-recovered").value),rejected=Number(el("q-rejected").value),inRework=Number(el("q-pending").value);try{if([inspected,failed,recovered,rejected,inRework].some(v=>!Number.isFinite(v)||v<0)||failed>inspected)throw new Error("Counts are invalid");qualityBalance({failed,recovered,rejected,inRework});const q={id:makeId(),inspected,failed,recovered,rejected,inRework,createdAt:new Date().toISOString()};pilot.quality.push(q);audit("QUALITY_COHORT_ADDED",{cohortId:q.id,inspected,failed});persist();el("quality-status").textContent="Quality cohort saved; physical-unit balance passed.";refresh();}catch(err){el("quality-status").textContent=`Not saved: ${err.message}`;}};
el("correction-form").onsubmit=e=>{e.preventDefault();if(!requireOpen(el("correction-status")))return;const record=pilot.observations.find(x=>x.id===el("correction-select").value),reason=el("correction-reason").value.trim();if(!record||!reason){el("correction-status").textContent="Choose an observation and enter a reason.";return;}const good=Number(el("correct-good").value),wip=Number(el("correct-wip").value);if(!Number.isFinite(good)||good<0||!Number.isFinite(wip)||wip<0){el("correction-status").textContent="Correction values must be zero or positive.";return;}const previous={goodOutput:record.goodOutput,queueBefore:record.queueBefore};record.revisions.push({at:new Date().toISOString(),previous,next:{goodOutput:good,queueBefore:wip},reason});record.goodOutput=good;record.queueBefore=wip;audit("OBSERVATION_CORRECTED",{observationId:record.id,reason,previous,next:{goodOutput:good,queueBefore:wip}});persist();el("correction-status").textContent="Correction saved; original values remain in history.";refresh();};
el("intervention-form").onsubmit=e=>{e.preventDefault();if(!requireOpen())return;const event=pilot.events.find(x=>x.id===el("intervention-event").value),action=el("action-input").value.trim();if(!event||!action)return;event.intervention={action,outcome:el("outcome-select").value,recordedAt:new Date().toISOString()};audit("INTERVENTION_RECORDED",{eventId:event.id,action,outcome:event.intervention.outcome});persist();el("action-input").value="";refresh();};
el("close-shift").onclick=()=>{if(pilot?.mode!=="pilot"||pilot.status!=="OPEN")return;if(pilot.events.some(e=>!e.end)){el("shift-status").textContent="Cannot close: resolve open disturbance events first.";return;}pilot.status="CLOSED";audit("SHIFT_CLOSED",{actualGood:pilot.actualGood});persist();refresh();};
el("reopen-shift").onclick=()=>{if(pilot?.mode!=="pilot"||pilot.status!=="CLOSED")return;const reason=el("lifecycle-reason").value.trim();if(!reason){el("shift-status").textContent="Reopening requires a reason so history remains explainable.";return;}pilot.status="OPEN";audit("SHIFT_REOPENED",{reason});el("lifecycle-reason").value="";persist();refresh();};
el("demo-button").onclick=()=>{pilot=null;localStorage.removeItem(KEY);refresh();};
el("export-button").onclick=()=>{const payload=pilot?.mode==="pilot"?pilot:{mode:"demo",fixture},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`flow-pilot-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};

refresh();
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
